### PR TITLE
feat(metrics): add option to specify dataset.

### PR DESCRIPTION
**Pull request by asahaf**
Add option to specify data set under which metrics timeseries will be created under when pushing metrics to cognite.

### CODE REVIEW

**Review by nrehmanawan — APPROVED** [review]

**Review by mathialo — CHANGES_REQUESTED** [review]
Hi! And thanks for your contribution.

I think the linting will fail when it's run, but until then I think there are some style mistakes here. Run `pre-commit run --all` locally to fix them.

Also please update the changelog.

**Comment by asahaf** [comment]
I've fixed the style and updated change log. However, pre-commit reports errors that are not related to the updated files/classes

**Comment by mathialo** [comment]
The failing CI run is from the tests, and it's related to the updated files. This PR introduces a circular dependency which makes the tests (or anything else) incapable of importing anything from either module:

 * `cognite.extractorutils.metrics` depends on `cognite.extractorutils.configtools.elements` (imports `EitherIdConfig`)
 * `cognite.extractorutils.configtools.elements` depends on `cognite.extractorutils.metrics`  (it imports the pusher classes, of which `CognitePusher` uses `EitherIdConfig`)

This would cause an infinite recursion if the import system didn't catch it.

The `metrics` module can not depend on the `configtools.elements` module, neither should it. You should rewrite the change to the `CognitePusher` to take in an `EitherId` object instead of an `EitherIdConfig`, and in the  `start_pushers` method of `MetricsConfig`, you should initialize the `EitherId` from the `EitherIdConifg`. 

Hope that helps!

**Comment by asahaf** [comment]
@mathialo replaced `EitherIdConfig` with `EitherId`. pre-commit passing now

**Comment by mathialo** [comment]
Great!

The remaining failures seem to be related to some credentials needed for integration tests, which are not available to PRs from external repos. I'll merge this into an intermediate branch, and add a new PR from that branch.

**Comment by asahaf** [comment]
Thanks @mathialo

**Comment by mathialo** [comment]
When this merges, the feature should be released https://github.com/cognitedata/python-extractor-utils/pull/272

**Pull request merged**
